# 端口
server:
  port: 9002
  server:
    context-path: /
# 应用名称
spring:
  application:
    name: aaaa

eureka:
  instance:
    # 使用 ip 代替实例名
    prefer-ip-address: true
    # 实例的主机名
    hostname: ${spring.cloud.client.ip-address}
    # 实例的 ID 规则
    instance-id: 10.0.50.11
  client:
    serviceUrl:
      # 注册中心地址
      defaultZone: http://10.0.54.208:11000/eureka/